#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 1fda1bb7-0495-4bec-96f3-5bb2d88300af
# Source File: ChangeComputerName.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
XhcAAB+LCAAAAAAABADdmG1vIjcQx99X6new9kVfIWA5EpIeIIXNpaqSaxDkri8jszsBN1575fXe
QT99x/twF4JhvUk5pVWkKJD5e8YzP48fhjMI5RdQm0uqKcE/UibFyOu1fW/880+EDG8VWzJB+RXj
8AeNYRysqFhCIOMk06DMV+0kfRh2dgwL+eIvCDXRmwRG3nyTaojbfzIRya9p+0qquPjdIrZ/tcjn
Mp5+u2t+WiTIuM4UjARkWlHeItNswVl4DZs7+QhitBgM6El4cuqfv+tD9+zcIwJDGXkPON5u4B4J
V4xHCoVeIIVWkqfFtDHyqZIJKL0pR7gIQ0j0JNNaisoGrWbwAKgPoTRb5Aa31x7pVAN1qpH2jZxp
OQ8ph0sWgzDzxSBOW8R/5y79KCPwxlc4h1pNwBkIPWd/o6B31m+RXndQKzL1mEgVgZrrDTeu2Bqi
S0a5XNaKP9I1i9HfRK5RSHkK9RImmkrygo7tha4VzzVVeipTppkpb4AZwqmGCkDUau9grb1yWZDK
K7G7/fAFRy51N5JG+wK+N/8cdnLzSlu/lH5TMkswZUdfTkvjaCHX/qEVtJupGxnSIsGI98nZTnr2
FfWbOwdFCfaghwuoe+4guKOL30UEyFnfzXquZbIPyn10XDxUTJCi2A7KT2mOBGZswcEMMwOMUzGx
9MZ3KrMOUc/IjEZMFm3s6Jgo46voiLjANrfiMC6HgOlhGANbOfcxs+PbSVvQ43dNW7ThcAifnpt9
zoMJiTjG9AIOrIN8ZmlGed6/JzR8DCSX6tAIT3tVsILwEaKC3ciS3ftti+3WZTbBgsz/AKkzSM1m
8DpU+y9EtXR+dFZtnXQfq01ieuOsllP5/8A6X2Uafbyysfovbayl96Pj2m3SWpsE9cZ5rebSDNjn
H+vp/UHgBjLZTIO6m9chWn081vVcTnUFq98dOp8cz/Bo2tu9eR2i08m6uCRgPPabwb9z/HslmNtY
YkUfn6bwPv/m2aWkMWpmJj/iiqLRD14ZXK/7B6EzPevUGTqLZ2f6/EF+IW+En+3cuVVJk/Jv3cUS
3f0Tg9eW94YugB+9uNx4+WDu6C9pJ/mrSZ5ux3W03X/c28/zMBs1IX/3Vabpic7ehPKAyDTIG9Gv
x+hEb3YD+v4614gXEa5M15xIVMctMmPLle04/FxXPI/hmROj9ca3181IOx8YBqyL2wpbNTdnyAYn
jXc6p8aUQ/YLjZP3TsG8kX2uSl/tLrf94SJNIUb2IM0ffIedp+/p438ASR/Bt14XAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.148
     Generated on:       19/01/2019 16:56
     Generated by:       Fitoussi
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2018
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-ChangeComputerName_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formChangeComputerName = New-Object 'System.Windows.Forms.Form'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$radiobuttonStayOn = New-Object 'System.Windows.Forms.RadioButton'
	$radiobuttonRestart = New-Object 'System.Windows.Forms.RadioButton'
	$radiobuttonShutdown = New-Object 'System.Windows.Forms.RadioButton'
	$CopyPCName = New-Object 'System.Windows.Forms.Button'
	$textboxComputerName = New-Object 'System.Windows.Forms.TextBox'
	$labelEnterPCName = New-Object 'System.Windows.Forms.Label'
	$buttonOK = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formChangeComputerName_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$buttonOK_Click={
		if ($radiobuttonShutdown.Checked)
		{
			$AfterShow = "Shutdown"
		}
		if ($radiobuttonRestart.Checked)
		{
			$AfterShow = "Restart"
		}
		if ($radiobuttonStayOn.Checked)
		{
			$AfterShow = "Stay On"
		}
		if ($textboxComputerName_TextChanged)
		{
			#Take Computer name from text box
			$ComputerName = $textboxComputerName.Text
			
			#Ask if sure about new name
			Add-Type -AssemblyName PresentationCore, PresentationFramework
			$ButtonType1 = [System.Windows.MessageBoxButton]::YesNo
			$MessageIcon1 = [System.Windows.MessageBoxImage]::None
			$MessageBody1 = "Computer Name: $ComputerName `n`nAfter: $AfterShow"
			$MessageTitle1 = "Confirm Settings"
			$msgBoxInput1 = [System.Windows.MessageBox]::Show($MessageBody1, $MessageTitle1, $ButtonType1, $MessageIcon1)
			switch ($msgBoxInput1)
			{
				#If click yes
				'Yes' {
					#Edit Registry files for changing computer name
					New-PSDrive -name HKU -PSProvider "Registry" -Root "HKEY_USERS"
					
					Remove-ItemProperty -path "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" -name "Hostname"
					Remove-ItemProperty -path "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" -name "NV Hostname"
					Set-ItemProperty -path "HKLM:\SYSTEM\CurrentControlSet\Control\Computername\Computername" -name "Computername" -value $ComputerName
					Set-ItemProperty -path "HKLM:\SYSTEM\CurrentControlSet\Control\Computername\ActiveComputername" -name "Computername" -value $ComputerName
					Set-ItemProperty -path "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" -name "Hostname" -value $ComputerName
					Set-ItemProperty -path "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" -name "NV Hostname" -value $ComputerName
					Set-ItemProperty -path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -name "AltDefaultDomainName" -value $ComputerName
					Set-ItemProperty -path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -name "DefaultDomainName" -value $ComputerName
					#Set-ItemProperty -path "HKU:\.Default\Software\Microsoft\Windows Media\WMSDK\General" -name "Computername" -value $ComputerName
					
					#Restart or Shutdown
					if ($radiobuttonRestart.Checked)
					{
						Restart-Computer
					}
					if ($radiobuttonShutdown.Checked)
					{
						Stop-Computer
					}
				}
				#If click No
				'No' {
					## Do nothing
				}
			}
		}
	}
	
	$radiobuttonStayOn_CheckedChanged={
		#TODO: Place custom script here
		
	}
	
	$radiobuttonRestart_CheckedChanged={
		#TODO: Place custom script here
		
	}
	
	$radiobuttonShutdown_CheckedChanged={
		#TODO: Place custom script here
		
	}
	
	$CopyPCName_Click = {
		#TODO: Place custom script here
		$CurrentComputerName = $env:computername
		$textboxComputerName.Text = $CurrentComputerName
	}
	
	$textboxComputerName_TextChanged={
		#TODO: Place custom script here
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formChangeComputerName.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$radiobuttonStayOn.remove_CheckedChanged($radiobuttonStayOn_CheckedChanged)
			$radiobuttonRestart.remove_CheckedChanged($radiobuttonRestart_CheckedChanged)
			$radiobuttonShutdown.remove_CheckedChanged($radiobuttonShutdown_CheckedChanged)
			$CopyPCName.remove_Click($CopyPCName_Click)
			$textboxComputerName.remove_TextChanged($textboxComputerName_TextChanged)
			$buttonOK.remove_Click($buttonOK_Click)
			$formChangeComputerName.remove_Load($formChangeComputerName_Load)
			$formChangeComputerName.remove_Load($Form_StateCorrection_Load)
			$formChangeComputerName.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formChangeComputerName.SuspendLayout()
	$groupbox1.SuspendLayout()
	#
	# formChangeComputerName
	#
	$formChangeComputerName.Controls.Add($groupbox1)
	$formChangeComputerName.Controls.Add($CopyPCName)
	$formChangeComputerName.Controls.Add($textboxComputerName)
	$formChangeComputerName.Controls.Add($labelEnterPCName)
	$formChangeComputerName.Controls.Add($buttonOK)
	$formChangeComputerName.AcceptButton = $buttonOK
	$formChangeComputerName.AutoScaleDimensions = '6, 13'
	$formChangeComputerName.AutoScaleMode = 'Font'
	$formChangeComputerName.ClientSize = '284, 207'
	$formChangeComputerName.FormBorderStyle = 'FixedDialog'
	$formChangeComputerName.MaximizeBox = $False
	$formChangeComputerName.MinimizeBox = $False
	$formChangeComputerName.Name = 'formChangeComputerName'
	$formChangeComputerName.StartPosition = 'CenterScreen'
	$formChangeComputerName.Text = 'Change Computer Name'
	$formChangeComputerName.add_Load($formChangeComputerName_Load)
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($radiobuttonStayOn)
	$groupbox1.Controls.Add($radiobuttonRestart)
	$groupbox1.Controls.Add($radiobuttonShutdown)
	$groupbox1.Location = '6, 58'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '272, 109'
	$groupbox1.TabIndex = 4
	$groupbox1.TabStop = $False
	$groupbox1.Text = 'After Name Change'
	$groupbox1.UseCompatibleTextRendering = $True
	#
	# radiobuttonStayOn
	#
	$radiobuttonStayOn.Location = '20, 79'
	$radiobuttonStayOn.Name = 'radiobuttonStayOn'
	$radiobuttonStayOn.Size = '104, 24'
	$radiobuttonStayOn.TabIndex = 2
	$radiobuttonStayOn.Text = 'Stay On'
	$radiobuttonStayOn.UseCompatibleTextRendering = $True
	$radiobuttonStayOn.UseVisualStyleBackColor = $True
	$radiobuttonStayOn.add_CheckedChanged($radiobuttonStayOn_CheckedChanged)
	#
	# radiobuttonRestart
	#
	$radiobuttonRestart.Location = '20, 49'
	$radiobuttonRestart.Name = 'radiobuttonRestart'
	$radiobuttonRestart.Size = '104, 24'
	$radiobuttonRestart.TabIndex = 1
	$radiobuttonRestart.Text = 'Restart'
	$radiobuttonRestart.UseCompatibleTextRendering = $True
	$radiobuttonRestart.UseVisualStyleBackColor = $True
	$radiobuttonRestart.add_CheckedChanged($radiobuttonRestart_CheckedChanged)
	#
	# radiobuttonShutdown
	#
	$radiobuttonShutdown.Location = '20, 19'
	$radiobuttonShutdown.Name = 'radiobuttonShutdown'
	$radiobuttonShutdown.Size = '104, 24'
	$radiobuttonShutdown.TabIndex = 0
	$radiobuttonShutdown.Text = 'Shutdown'
	$radiobuttonShutdown.UseCompatibleTextRendering = $True
	$radiobuttonShutdown.UseVisualStyleBackColor = $True
	$radiobuttonShutdown.add_CheckedChanged($radiobuttonShutdown_CheckedChanged)
	#
	# CopyPCName
	#
	$CopyPCName.Location = '12, 29'
	$CopyPCName.Name = 'CopyPCName'
	$CopyPCName.Size = '86, 23'
	$CopyPCName.TabIndex = 3
	$CopyPCName.Text = 'Copy Name'
	$CopyPCName.UseCompatibleTextRendering = $True
	$CopyPCName.UseVisualStyleBackColor = $True
	$CopyPCName.add_Click($CopyPCName_Click)
	#
	# textboxComputerName
	#
	$textboxComputerName.Location = '104, 6'
	$textboxComputerName.Name = 'textboxComputerName'
	$textboxComputerName.Size = '174, 20'
	$textboxComputerName.TabIndex = 2
	$textboxComputerName.add_TextChanged($textboxComputerName_TextChanged)
	#
	# labelEnterPCName
	#
	$labelEnterPCName.AutoSize = $True
	$labelEnterPCName.Location = '12, 9'
	$labelEnterPCName.Name = 'labelEnterPCName'
	$labelEnterPCName.Size = '86, 17'
	$labelEnterPCName.TabIndex = 1
	$labelEnterPCName.Text = 'Enter PC Name:'
	$labelEnterPCName.UseCompatibleTextRendering = $True
	#
	# buttonOK
	#
	$buttonOK.Anchor = 'Bottom, Right'
	$buttonOK.DialogResult = 'OK'
	$buttonOK.Location = '197, 172'
	$buttonOK.Name = 'buttonOK'
	$buttonOK.Size = '75, 23'
	$buttonOK.TabIndex = 0
	$buttonOK.Text = '&OK'
	$buttonOK.UseCompatibleTextRendering = $True
	$buttonOK.UseVisualStyleBackColor = $True
	$buttonOK.add_Click($buttonOK_Click)
	$groupbox1.ResumeLayout()
	$formChangeComputerName.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formChangeComputerName.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formChangeComputerName.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formChangeComputerName.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formChangeComputerName.ShowDialog()

} #End Function

#Call the form
Show-ChangeComputerName_psf | Out-Null
